service:
  elasticsearch:
    image: elastic/elasticsearch:8.18.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:9.0.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
  logstash:
    image: logstash:9.0.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
  beats:
    image: elastic/filebeat:8.18.4
    container_name: filebeat
    volumes:
      - ./filebeat/config:/usr/share/filebeat/config
      - ./logs:/var/log
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: filebeat -e -strict.perms=false