services:
  elasticsearch:
    image: elastic/elasticsearch:8.18.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.18.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
  logstash:
    image: logstash:8.18.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
  beats:
    image: elastic/filebeat:8.18.4
    container_name: beats
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: filebeat -e --strict.perms=false
volumes:
  esdata:
    driver: local