apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-ca
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs