name: Main Workflow

on:
  push:
    # branches:
    #   - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run build
        run: docker build -t ca-devopsua5:0.1-ubuntu ./21/ 
      
      - name: Changes pushed from machine
        run: echo "This was written on the local machine" 