name: Print Hello World

on:
    push:
        # branches:
        #     - main

jobs:
    print-message:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
                run: echo "heloo world"