name: Main Workflow

on:
  push:
    branches:
      - main
    paths:
      - '21/**' # Ignore changes in the 21 directory
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run build
        run: docker build -t serbentas/ca-devopsua5:0.1-ubuntu ./21/ 
      
      - name: Docker login
        run: echo "${{ secrets.dockerhubpassword }}" | docker login -u "${{ secrets.dockerhubusername }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push serbentas/ca-devopsua5:0.1-ubuntu
  test:
    needs: build # Run after the build job completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: docker run --rm serbentas/ca-devopsua5:0.1-ubuntu /app/test.sh
  prepare-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Prepare infrastructure
        run: |
          echo ./22/createVM.sh