name: 01.0 Full Run

on:
    workflow_dispatch:

jobs:
    checkout:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
    create_infra:
      permissions:
        id-token: write
        contents: read
      # Step 1: Run terraform02.yml
      uses: ./.github/workflows/terraform02.yml

    prepare_docker:
      secrets:
        AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
      permissions:
        id-token: write
        contents: read
      needs: create_infra
      # Step 2: Prepare Docker VM
      uses: ./.github/workflows/PrepareDockerVM.yml

    run_container:
      secrets:
        AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
      permissions:
        id-token: write
        contents: read
      needs: [create_infra, prepare_docker]   
      # Step 3: Run Container
      uses: ./.github/workflows/RunContainer.yml
            