name: 22. Docker Build and Push
on:
  push:
    branches:
      - dev
    paths:
      - '22/**' # Trigger only if files in the 21 directory are changed
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: '0.1-ubuntu'
env:
  repository: serbentas
  image: ca-devopsua5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag
        id: check_tag
        run: |
          if [[ -z "${{ inputs.tag }}" ]]; then
            echo "Tag was left empty. Assuming default tag: 0.1-ubuntu"
            echo "tag=0.1-ubuntu" >> $GITHUB_ENV
          else

            echo "tag=${{ inputs.tag }}" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run build
        run: docker build -t ${{ env.repository }}/${{ env.image }}:${{ env.tag }} ./21/ 
        
      - name: Docker login
        run: echo "${{ secrets.dockerhubpassword }}" | docker login -u "${{ secrets.dockerhubusername }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push ${{ env.repository }}/${{ env.image }}:${{ env.tag }}
    
  infra:
    needs: build # Run after the build job completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: AZURE CLI Login
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare infrastructure
        run: |
          echo ./22/createVM.sh
