name: 01.2 Prepare Docker VM with ansible

on:
  workflow_call:
    inputs:
      workdir:
        type: string
        description: Path to Ansible code
        default: 54/ansible
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # working-directory: ${{ github.event.inputs.workdir }}
        working-directory: 54/ansible

    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: arn:aws:iam::034362059178:role/github-actions-role-ua5
            aws-region: eu-central-1

        - name: Install Ansible and Dependencies
          run: |
            python3 -m pip install ansible ansible-core boto3 botocore
        
        - name: Install amazon-aws pluigin
          run : ansible-galaxy collection install amazon.aws

        - name: Set up SSH key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_EC2_SSH_KEY }}"
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/ca_key.pem
            chmod 600 ~/.ssh/ca_key.pem
            chmod 600 ~/.ssh/id_rsa          

        - name: Prepare Docker VM with ansible
          run: ansible-playbook -u ubuntu --key ~/.ssh/ca_key.pem playbook.yml